[package]
name = "translation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.74.2"
anyhow = "1.0.68"
ndarray = "0.15.6"
tesseract = "0.12.0"